### ISSUE TITLE
Коде ревью к ДЗ

### ISSUE THREAD

**Issue by DWD73** [ZyuDev/Otus.CSharp.HW7#1]
Хорошая работа. Понравилась реализация функции [IsDocumentsReady()](https://github.com/ZyuDev/Otus.CSharp.HW7/blob/ac2a50a6b60eeaa2be0ad20991c2b1c2f27675a8/HW7/DocumentsReceiver.cs#L51).

**Comment by ZyuDev** [comment]
Спасибо за Review.
